server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: authenticate-service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5429/authenticate
    username: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog.yml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/NewRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  converter:
    resource-id: authentication-api-client
    principleName: preferred_username